In [6]:
import numpy as np
a=np.array([1,2,3])
a
# print(type(a))

array([1, 2, 3])

### Fast or slow between list or array

In [8]:
%timeit [j**4 for j in range(1,9)]

2.14 μs ± 22.4 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [10]:
import numpy as py 
%timeit np.arange(1,9)**4
# faster than list 

1.88 μs ± 25.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


#### user Input in array

In [12]:
l=[]
for i in range(1,5):
    a=int(input("enter the value"))
    l.append(a)
print(np.array(l))

enter the value 23
enter the value 34
enter the value 78
enter the value 12


[23 34 78 12]


## 1 to multidimension array

In [18]:
# 1 dimension array
n=[1,2,3,4]
y=np.array([n])
print(y)
print(y.ndim)

[[1 2 3 4]]
2


In [24]:
# 2 dim array
ar2 = np.array([[1,2,3,4],[1,2,7,8]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [1 2 7 8]]
2


In [23]:
# 3 dim array
ar2 = np.array([[[1,2,3,4],[1,2,7,8]]])
print(ar2)
print(ar2.ndim)

[[[1 2 3 4]
  [1 2 7 8]]]
3


In [33]:
# multidimensin array
import numpy as np
arn= np.array([1,3,4,5],ndmin=10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 3 4 5]]]]]]]]]]
10
