In [3]:
import numpy as np
a=np.array([1,2,3])
a
# print(type(a))

array([1, 2, 3])

### Fast or slow between list or array

In [9]:
%timeit [j**4 for j in range(1,9)]

2.19 μs ± 24 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [8]:
%timeit np.arange(1,9)**4

1.82 μs ± 21.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [16]:
from numpy import *
a=arange(2,10,2)
print(a)
print()
arr = np.arange(0, 5, 0.5)
print(arr)

[2 4 6 8]

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


### How to create array

In [31]:
a=np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


### user input an array

In [37]:
l=[]
a=int(input('How many numbers of add into array?'))
for i in range(a):
    print('enter number :',end='')
    l.append(int(input()))
print(l)  # printlist 
print(np.array(l))   # print array 

How many numbers of add into array? 4


enter number :

 2


enter number :

 4


enter number :

 6


enter number :

 7


[2, 4, 6, 7]
[2 4 6 7]


In [40]:
#another way
st=[]
a=int(input('how many number you want enter?'))
for i in range(a):
    a=int(input('enter number : '))
    st.append(a)
print(np.array(st))


how many number you want enter? 4
enter number :  2
enter number :  4
enter number :  5
enter number :  6


[2 4 5 6]


In [46]:
## check the dimension
a=[1,2,3,4]
y=np.array([a])
print(y)
print(y.ndim)  #how many dimension  
print(type(a))

[[1 2 3 4]]
2
<class 'list'>


In [49]:
# create multidimension
ar=np.array([1,2,3,5],ndmin=10)
print(ar)
print(ar.ndim)

[[[[[[[[[[1 2 3 5]]]]]]]]]]
10


In [53]:
#zeros
ar_zero=np.zeros(5)
print(ar_zero)
print()
ar_zero1=np.zeros((3,4))
print(ar_zero1)

[0. 0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [75]:
# ones
one=np.ones(3)
print(one)

print()

# empty array
emp=np.empty(4)
print(emp)

print()

# range element
ar_m= np.arange(4)
print(ar_m)

print()

# Diangonal element
ar_di=np.eye(3)
print(ar_di)
print()
ar_di=np.eye(5,3)
print(ar_di)

print()

# linspace 
ar_li=np.linspace(0,10,num=5)
print(ar_li)

[1. 1. 1.]

[0.0e+000 4.9e-324 9.9e-324 1.5e-323]

[0 1 2 3]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]

[ 0.   2.5  5.   7.5 10. ]


In [87]:
var =np.random.rand(10)
print(var)
print()
var2=np.random.rand(2,5)  #2 row and 5 column
print(var2)
print()

var3=np.random.randn(5)
print(var3)
print()

var4=np.random.ranf(4)
print(var4)
print()

# var5=np.random.randint(min,max,total_value)
var5=np.random.randint(5,20,5)
print(var5)

[0.79679625 0.23320921 0.72885117 0.67743397 0.86458595 0.19543231
 0.89000322 0.40110107 0.9666394  0.69993739]

[[0.95671939 0.34749028 0.75190364 0.93010897 0.59873518]
 [0.82653712 0.7520373  0.69054919 0.77411819 0.63961284]]

[ 0.64134854  0.5091255  -0.34835408 -0.06531347 -0.42134545]

[0.21734468 0.98339994 0.83328757 0.69793424]

[ 8 13  7 16  7]


## Datatype in array

In [94]:
var6=np.array([1,2,3,5,6,7])
print("Datatype: ",var6.dtype)
var7=np.array([1.0,3.5,7.8])
print("Datatype: ",var7.dtype)
var8=np.array(["a","b","c"])
print("Datatype: ",var8.dtype)
var9=np.array(["a","j","v",1,5])
print("Datatype: ",var9.dtype)

Datatype:  int64
Datatype:  float64
Datatype:  <U1
Datatype:  <U21


## Arithmetic operation 

In [130]:
a=3
b=6
c=np.add(a,b)
print(c)
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.mod(a,b))
print(np.power(a,b))
addi = np.array([1,2,3,4]) 
re=np.reciprocal(addi)  #number ne reverse kare
print(re)

9
-3
18
0.5
3
729
[1 0 0 0]


In [117]:
add = np.array([1,2,3,4])
print(add)
varadd=add+3
print(varadd)
print()
add1=np.array([2,3,4,5])
print(add1)
print(add+add1)
print()
# using function
addition=np.add(add,add1)
print(addition)

[1 2 3 4]
[4 5 6 7]

[2 3 4 5]
[3 5 7 9]

[3 5 7 9]


In [120]:
var11=np.array([[1,2,3,4],[1,2,3,4]])
var12=np.array([[1,2,3,4],[1,2,3,4]])
print(var2)
print(var2.ndim)
varadd1=np.add(var11,var12)
print(varadd1)

[[1 2 3 4]
 [1 2 3 4]]
2
[[2 4 6 8]
 [2 4 6 8]]


In [132]:
add = np.array([1,2,3,4,5,8,90])
print(add)
print(np.min(add))
print(np.max(add))
print(np.sqrt(add))
print("min : ",np.min(add),np.argmin(add))
print("max : ",np.max(add),np.argmax(add))

[ 1  2  3  4  5  8 90]
1
90
[1.         1.41421356 1.73205081 2.         2.23606798 2.82842712
 9.48683298]
min :  1 0
max :  90 6


In [138]:
var1=np.array([[2,1,3],[60,8,9]])
print(np.max(var1,axis=1))


[ 3 60]


In [140]:
var1=np.array([2,1,3])
print(np.sin(var1))
print(np.cos(var1))
print(np.cumsum(var1))

[0.90929743 0.84147098 0.14112001]
[-0.41614684  0.54030231 -0.9899925 ]
[2 3 6]


## shape

In [155]:
var1=np.array([[2,1,3],[6,8,9]])
print(var1.shape)

var2=np.array([1,3,2,4],ndmin=4)
print(var2)
print(var2.ndim)

(2, 3)
[[[[1 3 2 4]]]]
4


In [151]:
var9=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var9)

x1=(var9.ndim)
x1=var9.reshape(2,3,2)
print(x1)
one=x1.reshape(-1)
print(one)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [154]:
var6=np.array([1,2,3,4,5,6])
print(var6.shape)

(6,)


In [156]:
var1=np.array([[1],[2],[3]])
print(var1.shape)

(3, 1)


In [157]:
print(var6+var1)

[[2 3 4 5 6 7]
 [3 4 5 6 7 8]
 [4 5 6 7 8 9]]


### copy v/s view


In [160]:
x=np.array([1,2,3,4,5,6])
c=x.copy()
x[1]=4
print(x)
print(c)

[1 4 3 4 5 6]
[1 2 3 4 5 6]


In [165]:
y=np.array([4,5,6,7])
z=y.view()
y[1]=40
print(y)
print(z)

[ 4 40  6  7]
[ 4 40  6  7]


In [178]:
from turtle import*
bgcolor("black")
speed(0)
pensize(2)
hideturtle()
for i in range(90):
    color("olive")
    circle(i)
    color("cyan")
    circle(i*1.5)
    right(5)
    forward(3)
done()

In [3]:
from turtle import *
import colorsys
speed(0)
bgcolor("black")
h=0
for i in range(16):
    for j in range(18):
        c=colorsys.hsv_to_rgb(h,1,1)
        color(c)
        h+=0.005
        rt(90)
        circle(150-j*6,90)
        lt(90)
        circle(150-j*6,90)
        rt(180)
    circle(40,24)
done()

In [186]:
# find index
var=np.array([8,9,0,6])
print(var[1])
print(var[-1])
x=np.array([[[1,2],[6,7]]])
print(x)
print(x.ndim)
print(x[0,1,1])

9
6
[[[1 2]
  [6 7]]]
3
7


In [195]:
var=np.array([1,2,3,4,5,6])
print("2 to 5",var[1:5])
print()
y=np.array([[[9,8,7,6],[11,12,32,8]]])
print(y[0,1:4])

2 to 5 [2 3 4 5]

[[11 12 32  8]]


## Iterating

In [196]:
var=np.array([8,9,0,6])
for i in var:
    print(i)

8
9
0
6


In [200]:
y=np.array([[9,8,7,6],[11,12,32,8]])
for j in y:
    for k in j:
        print(k)
    

9
8
7
6
11
12
32
8


In [202]:
y=np.array([[[9,8,7,6],[11,12,32,8]]])
print(y)
for i in np.nditer(y):
    print(i)

[[[ 9  8  7  6]
  [11 12 32  8]]]
9
8
7
6
11
12
32
8


In [208]:
for i in np.nditer(y,flags=['buffered'],np.dtype==["s"]):
    print(i)

SyntaxError: positional argument follows keyword argument (204588942.py, line 1)

In [206]:
# with index iterating
for i,d in np.ndenumerate(y):
    print(i,d)

(0, 0, 0) 9
(0, 0, 1) 8
(0, 0, 2) 7
(0, 0, 3) 6
(0, 1, 0) 11
(0, 1, 1) 12
(0, 1, 2) 32
(0, 1, 3) 8


In [210]:
var=np.array([8,9,0,6,1,2])
print(var)
ar=np.array_split(var,3)
print(ar)
print(ar[0])


[8 9 0 6 1 2]
[array([8, 9]), array([0, 6]), array([1, 2])]
[8 9]


In [8]:
# filter 
import numpy as np
var_3=np.array(["a","b","c","d"])
f=[True,False,False,True]
new_a=var_3[f]
print(new_a)

['a' 'd']


## Arithmetic function

In [10]:
v=np.array([1,2,3,4,5])
np.random.shuffle(v)
print(v)

[5 1 3 4 2]


In [13]:
v=np.array([1,2,3,4,5,4,3,0])
x=np.unique(v)
print(x)

[0 1 2 3 4 5]


In [14]:
v=np.array([1,2,3,4,5,4,3,0])
x=np.unique(v,return_index=True)
y=np.unique(v,return_counts=True)
print(x)
print(y)

(array([0, 1, 2, 3, 4, 5]), array([7, 0, 1, 2, 3, 4]))
(array([0, 1, 2, 3, 4, 5]), array([1, 1, 1, 2, 2, 1]))


In [28]:
# insert & delete
var1=np.array([[1,2,3],[1,2,3]])
print(var1)
print()
v1=np.insert(var1,1,[22,33,44],axis=0)
print(v1)
print()
v1=np.append(var1,[[23,45,66]],axis=0)
print(v1)

[[1 2 3]
 [1 2 3]]

[[ 1  2  3]
 [22 33 44]
 [ 1  2  3]]

[[ 1  2  3]
 [ 1  2  3]
 [23 45 66]]


## Matrix

In [37]:
import numpy as np
var =np.matrix([[1,2,3],[1,2,3]])
var1 =np.matrix([[1,2,3],[1,2,3]])
print(type(var))
print(var+var1)
print()


<class 'numpy.matrix'>
[[2 4 6]
 [2 4 6]]



In [39]:
var =np.matrix([[1,2],[3,4]])
var1 =np.matrix([[1,2],[3,4]])
print(var.dot(var1))

print()
var =np.matrix([[4,5],[8,9]])
var1 =np.matrix([[3,2],[4,5]])
print(var.dot(var1))

[[ 7 10]
 [15 22]]

[[32 33]
 [60 61]]
